### PR TITLE
Control the maximum # of flanking sequences via the command line.

### PR DESCRIPTION
**Pull request by nh13**
Also adds an option to attempt to filter infrequently seen flanking
sequences.

### CODE REVIEW

**Comment by tfwillems** [comment]
Thanks for contributing this @nh13!

In general I'm aiming to keep the command line as simple as possible, so I'd like to avoid adding 2 extra command line options if possible. It'd be great if you could describe your motivation for adding these 2 options. Did you notice that the default behavior was filtering too many flanks, or was it not filtering enough and taking too long to run? What kind of datasets did you observe this behavior for?

Thanks!

**Comment by nh13** [comment]
@tfwillems

My application is genotyping individual samples across the various [CODIS](https://github.com/fulcrumgenomics/fgstr/wiki/CODIS-annotations) markers using [duplex sequencing](https://www.ncbi.nlm.nih.gov/pubmed/25299156).  I am performing joint calling by calling the set of reads from each source molecule independently, then "merging" the calls for a final genotype (I could use your help on that if you're interested).  Interestingly, many of the sites are (~4/20) have an issue with too many flanking sequences, in my case, up to `20`.  I found that since I was only genotyping a small set of targets, I could increase the # of flanking sequences and run-time would still be acceptable.  Also, I found that many of the flanking sequences (haplotypes) were observed only once, due to the non-trivial raw error rate combined with rather long STRs (some >100bp).  Therefore, I could ignore flanking sequences that were observed only a few times relative to the more frequent alternatives.

The ability to control the # of flanking sequences is definitely a must, and the heuristic filter is a nice-to-have for run-time.  I totally understand keeping the command line simple, but given reasonable defaults, I don't think it is such a bad thing, this coming from a person who has developed many widely used bioinformatic tools.  If you don't want to merge this, likely I will unfortunately need to maintain a fork, which I really really don't want to do.

Also, regarding having two repositories, could you instead just have two branches?  A `devel` branch for unstable but bleeding edge features, and `master` for stable versions?  It was a bit confusing.

Thank-you for your responses and the software that works very well!

**Comment by nh13** [comment]
@tfwillems would it be easier to have `--codis` option rather than these granular options?

**Comment by nh13** [comment]
@tfwillems bump, any thoughts on the `--codis` option?  I am having _a lot_ of success with this update.

**Comment by tfwillems** [comment]
Hi @nh13 ,

I'm glad to hear that with these slight alterations you've found HipSTR useful.

Sorry I haven't had a chance to address the changes just yet. I've been quite busy with work but hope to pull in a few fixes for HipSTR in the next week or so.

The original limit on the number of flanking sequences was meant to maintain computational and memory tractability. We've encountered loci where these filters fail, but for most STRs, the default settings are fine. Of course, the CODIS markers are not typical due to their longer lengths and exceptional variability. As a result, the ~20% CODIS issue rate may partially be driven by the extremely high variability in these regions. 

However, it may also partially be due to the uniqueness of your application. As you pointed out, any sequencing errors introduced in regions around the STR during the first PCR round of duplex sequencing will generate false positive polymorphic flanks for all reads from that molecule. This isn't really an issue during WGS/WES, but my hunch is that this may be playing a role in generating too many flanking sequences for you application.

It sounds like you've been quite clever in terms of limiting these false positives by filtering rarely observed flanks. However, my concern is that this wouldn't be suitable for most non-duplex based applications. I'd like to maintain the specificity of HipSTR as much as possible and I think considering candidate flanks, even if only observed in one sample, is important to doing so. Otherwise, we may generate errors during variant calling that are specific to samples with filtered flanking sequences.


I'm happy to pull in the changes that add the command line option to specify the maximum number of flanking haplotypes. However, I'm less inclined to incorporate the filtering option, as the 1/2 as frequent cutoff seems relatively arbitrary. 

One possibility would be that instead of skipping the locus entirely when there are too many flanking sequences, we merely avoid genotyping samples with candidate flanking sequences that have been filtered. If this would be acceptable, I'd be happy to accept your PR if you modified it accordingly.

Many thanks again for these suggestions!

**Comment by nh13** [comment]
@tfwillems Thanks for your thoughtful and detailed response.  I would like to test and see if avoiding genotyping samples with filtered candidate flanking sequences gives me similar sensitivity when run.  Looking briefly at the code, I am honestly having a hard time figuring out how to implement flagging which samples should be genotyped from within the stutter processor.  Any hints?

One caveat with skipping genotyping individual samples is that I can see two cases where I'd still like the genotypes:

1. when trying to estimate the allele frequency across the "samples" (duplexes) for each alleles.  Some individuals have triallelic sites, as well as we may even want to support complex mixtures (I am at it again).
2. when trying to estimate the observed stutter, so we want to genotype as many "samples" (duplexes) as possible.

Would you be me open to changing the `--filter-flank-haps` from a `boolean` to a `float/double`?  The option by default would be `1.0` (filter all when we hit the max), but could be set to remove half (`0.5`) or more.  Since the defaults don't change the results, I would hope that this would be more acceptable.  

As for the application, typing the CODIS markers is done a lot, and while the underlying way we are using HipSTR is niche, the desire to genotype those sites and the challenges that come with it, are not.

**Comment by tfwillems** [comment]
Hi @nh13,

Based on your initial suggestions, I've gone ahead and added more flank filtering functionality. It was largely based on your initial changes, with a few alterations. HipSTR now filters a flanking sequence if it's present in a fraction of samples below the threshold specified by the *--min-flank-freq* command line option and allows as many flanks as specified by the *--max-hap-flanks* option.

Samples with candidate flanks below the desired frequency are not genotyped to avoid any loss of precision in general-purpose genotyping applications. These changes were all made in the most recent [commit](12dffc42280830c14d0a7f23312bcb4e415bb9c8) in the *assemble_flanks()* function in *seq_stutter_genotyper.cpp*. Hopefully you can set a reasonable cutoff for *--min-flank-freq* based on the expectation that you only have a certain number of candidate flanks (and the other candidate flanks are likely just sequencing error)

**Pull request closed without merging**
